name: Publish deb

on:
  release:
    types: [published]

permissions:
  contents: write
  checks: write

jobs:
  deb-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build deb package
        if: success()
        run: |
          npm ci
          npm run build
          npx node-deb -- dist/
      - name: Upload deb package to Github Release
        if: success()
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["etherproxy_*deb"]'
      - name: Upload deb package to Gemfury
        if: success()
        run: |
          for p in etherproxy_*deb; do curl -F package=@"${p}" https://${{ secrets.GEMFURY_TOKEN }}@push.fury.io/ethersphere/; done
